### PR TITLE
remove imports to fix console warnings

### PR DESCRIPTION
**Pull request by MadelinTom**
remove unused imports to fix console warnings

### CODE REVIEW

**Review by matejoslav — APPROVED** [review]

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210712-152753 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210712-152753") to [test](https://console.bluemix.net/apps/fb71f19b-b25b-41a0-afbb-0c3b9336fbec?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 196b262da5f13cf5fca74cc7d97e64fb8ef9ea61

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210712-154540 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210712-154540") to [prod](https://console.bluemix.net/apps/830e9a40-1041-4364-97c8-5cebe7d7ea12?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 196b262da5f13cf5fca74cc7d97e64fb8ef9ea61

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210715-190608 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210715-190608") to [dev](https://console.bluemix.net/apps/4402f067-7721-430c-88fb-e1b68fed3361?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit dd2f59c5118fb00f4005cca50441dc292e74447c

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210716-090706 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210716-090706") to [test](https://console.bluemix.net/apps/2cad90d4-d092-41e4-b067-4e23c89ed619?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commits dd2f59c5118fb00f4005cca50441dc292e74447c, b54b270aadcce30f3f7aad9618fbdf1491b477d7

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210720-152423 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210720-152423") to [prod](https://console.bluemix.net/apps/14223cd4-871d-4f82-bc5d-204618d9c0cf?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commits dd2f59c5118fb00f4005cca50441dc292e74447c, b54b270aadcce30f3f7aad9618fbdf1491b477d7

**Pull request merged**
