### PR TITLE
new landing page design

### PR DESCRIPTION
**Pull request by nicholasmorgan**

### CODE REVIEW

**Review by matejoslav — DISMISSED** [review]
The social media icons colour + shape + spacing need to follow brand guidelines.

Twitter example:
https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2_0.pdf

https://about.twitter.com/en_gb/company/brand-resources.html

**Review by AntonioDaria — APPROVED** [review]
Looks good on both desktop and mobile.  Good to go
In regard to the social media icons and branded guidelines i think it reflects exactly what was on the designs. In my opinion the designers will need to change the designs for us to reflect the changes.

**Comment by matejoslav** [comment]
Screenshot from 2021-01-05 21-12-37

**Comment by MadelinTom** [comment]
This looks good to me - images are slightly blury but not noticably (maybe its your 4k monitor @matejoslav).

I would be happy to merge!

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210107-103027 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210107-103027") to [dev](https://console.bluemix.net/apps/28465004-237e-4008-a01e-503032bea3ed?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit cdf0579484f457aa40f6c4d666bade531b2bf49c

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210107-145625 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210107-145625") to [test](https://console.bluemix.net/apps/e32d4b6f-bcb4-49a9-ba27-8d665876ebcd?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit cdf0579484f457aa40f6c4d666bade531b2bf49c

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747") to [test](https://console.bluemix.net/apps/1d38058e-0941-478d-ab73-1c5c09e8e146?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit cdf0579484f457aa40f6c4d666bade531b2bf49c

**Pull request merged**
