### PR TITLE
Bring help page up to date with designs

### PR DESCRIPTION
**Pull request by MadelinTom**
Bring help page up to date with designs: https://www.figma.com/file/SfRqwuE3GEpM3RkgsH4VLC/Main?node-id=467%3A3375

### CODE REVIEW

**Review by matejoslav — CHANGES_REQUESTED** [review]
image

Mobile designs do not match.

image

iPad layout looks a little bit weird + menu on top on iPad appears to be squished (probably separate ticket)

image

Graphics in the blue section appears offset to the left (1080p screen width) (4k looks even weirder :D )

**Comment by matejoslav** [comment]
maybe some of the issues are resolved with the max width ticket

**Review by matejoslav — APPROVED** [review]
LGTM

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210114-123024 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210114-123024") to [dev](https://console.bluemix.net/apps/482aadce-fc96-4c36-a7ae-03f3a425160c?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 0f125c8bdf56547178551140311b8fa1d7a4a9be

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210119-174451 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210119-174451") to [test](https://console.bluemix.net/apps/ffe68851-6e56-40b0-80a3-554fcbfafe9d?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 0f125c8bdf56547178551140311b8fa1d7a4a9be

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747") to [test](https://console.bluemix.net/apps/1d38058e-0941-478d-ab73-1c5c09e8e146?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 0f125c8bdf56547178551140311b8fa1d7a4a9be

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944") to [prod](https://console.bluemix.net/apps/f1598887-083c-4cac-a3a3-4950b5d061d5?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 0f125c8bdf56547178551140311b8fa1d7a4a9be

**Pull request merged**
