### PR TITLE
Added Accordion

### PR DESCRIPTION
**Pull request by nicholasmorgan**
Drop down on results page https://trello.com/c/Lhtodrl8/252-drop-down-in-results-page

### CODE REVIEW

**Comment by matejocovskyibm** [comment]
Test files should be called something.spec.js or ts

**Comment by matejoslav** [comment]
Screenshot from 2021-06-17 16-10-07

**Comment by matejoslav** [comment]
Also on desktop, the text next to the arrow jumps left a little bit when the accordion is expanded, this is probably caused by the image but we should probably keep it in one place

**Review by matejoslav — CHANGES_REQUESTED** [review]
see previous comments

**Comment by MadelinTom** [comment]
> Also on desktop, the text next to the arrow jumps left a little bit when the accordion is expanded, this is probably caused by the image but we should probably keep it in one place

+1

This is what it looks like on firefox iPhone 6 emulator: 
image

Abit different to yours Matt

**Comment by MadelinTom** [comment]
Looks good!

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210618-094651 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210618-094651") to [dev](https://console.bluemix.net/apps/9a185853-f5e6-45ca-97a9-0b06c52619b2?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 9783169f9fe7e6cb7db97e66a2bb97b457ad71ab

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210708-095707 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210708-095707") to [test](https://console.bluemix.net/apps/8f252b81-8c47-42f1-9a5b-85e5a6523777?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 9783169f9fe7e6cb7db97e66a2bb97b457ad71ab

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210709-111250 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210709-111250") to [prod](https://console.bluemix.net/apps/0c01691f-fa4c-4f9f-83ab-49b1a0594f66?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 9783169f9fe7e6cb7db97e66a2bb97b457ad71ab

**Pull request merged**
