### PR TITLE
Database Environment Variables

### PR DESCRIPTION
**Pull request by piers-walter-ibm**
Added environment variables to the server which can override the hardcoded defaults.
Supported values can be found in `statics.ts`

### CODE REVIEW

**Review by MadelinTom — APPROVED** [review]
looks good

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210719-145414 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210719-145414") to [dev](https://console.bluemix.net/apps/0e2410ba-0cdb-47e7-a4df-4aac15f62466?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit bbb2dfe0fcd5bdb3a784bf0bb7e33ec5ed9245e0

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210720-140402 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210720-140402") to [test](https://console.bluemix.net/apps/cc15165c-b106-4f14-8abc-8afb9a441f1e?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit bbb2dfe0fcd5bdb3a784bf0bb7e33ec5ed9245e0

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210720-152423 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210720-152423") to [prod](https://console.bluemix.net/apps/14223cd4-871d-4f82-bc5d-204618d9c0cf?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit bbb2dfe0fcd5bdb3a784bf0bb7e33ec5ed9245e0

**Pull request merged**
