### PR TITLE
disable id like to help navbar and add modal

### PR DESCRIPTION
**Pull request by MadelinTom**
https://trello.com/c/nEK9gbmj/161-disable-id-like-to-help-from-navigation-menu

### CODE REVIEW

**Comment by matejoslav** [comment]
@MadelinTom should the navbar item be grayed out?

**Comment by MadelinTom** [comment]
As the NavLink now opens a Modal I thought not, but if so its an easy fix. Will raise on the Slack channel

**Review by matejoslav — APPROVED** [review]

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210219-125140 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210219-125140") to [dev](https://console.bluemix.net/apps/540dd3ad-9d05-4545-8e00-19ed36c23698?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit aa0a8b8c975ef7d107a3b72eaa5f4f3c48d0b60b

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210302-130622 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210302-130622") to [test](https://console.bluemix.net/apps/bef762e5-4952-4e16-a258-78b99b9fb66d?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit aa0a8b8c975ef7d107a3b72eaa5f4f3c48d0b60b

**Pull request merged**
