### PR TITLE
Change flashcards page from feedback on call

### PR DESCRIPTION
**Pull request by piers-walter-ibm**

### CODE REVIEW

**Review by matejoslav — CHANGES_REQUESTED** [review]
For some reason the loading now appears on the left side of the screen when loading flashcards

**Comment by piers-walter-ibm** [comment]
Thanks Matt, I've pushed a fix for that now, it's because I was changing the alignment CSS of the cards and didn't see the spinner

**Comment by matejoslav** [comment]
Screenshot from 2021-06-25 12-36-43

Ive got this weird gap in the cards section. I have also noticed that the text on figma is bit different to what we have now. I am not sure if this ticket should also deal with changing the flashcards text.

**Comment by matejoslav** [comment]
Screenshot from 2021-06-25 12-45-34

Also there is small gap on the edge cards and the text left side, hopefully you can see it, seems to be the margin that all cards have got set to 12px

**Comment by matejoslav** [comment]
Ticking the first cards seem to cause some cards to change positions
before:
Screenshot from 2021-06-25 12-48-52

after:
Screenshot from 2021-06-25 12-49-17

**Review by matejoslav — CHANGES_REQUESTED** [review]
see previous comments

**Comment by piers-walter-ibm** [comment]
Just pushed some changes for the bold text issue and the card spacing. For the issue you mentioned here: https://github.com/lebanon-relief-project/LRP-web-app/pull/136#issuecomment-868439011 it's a bit of a tricky one. The cards are one long flexbox column which I then get the height of and multiply by  0.4 to set to  the new height to generate the 3 columns. This was to match the design with  the cards "interlocking". If I made it a row which wrapped then you can't get  the interlocking  card effect but it does mean  that sometimes the 3rd column can be a bit shorter than the others

**Comment by matejoslav** [comment]
> 
> 
> Just pushed some changes for the bold text issue and the card spacing. For the issue you mentioned here: [#136 (comment)](https://github.com/lebanon-relief-project/LRP-web-app/pull/136#issuecomment-868439011) it's a bit of a tricky one. The cards are one long flexbox column which I then get the height of and multiply by 0.4 to set to the new height to generate the 3 columns. This was to match the design with the cards "interlocking". If I made it a row which wrapped then you can't get the interlocking card effect but it does mean that sometimes the 3rd column can be a bit shorter than the others

Okay that is fine, what do we want to do with the texts of the flashcards not matching what is on figma? We can discuss during standup, changing the text is just db change.

**Review by matejoslav — APPROVED** [review]

**Comment by piers-walter-ibm** [comment]
Hi @matejoslav, I've changed some breakpoints on the card page to help make it flow a bit better, this involved a new breakpoint called `ipadprolandscape` set to `1366px`. This is used to reduce the number of card columns down to two to make sure they're not too narrow as well as to decrease the opacity of the swirly images at the top  to fill the space without it interfering with the text too badly.

**Review by matejoslav — APPROVED** [review]
LGTM

**Pull request merged**
