### PR TITLE
Fix a variety of snags

### PR DESCRIPTION
**Pull request by nicholasmorgan**
https://trello.com/c/nEK9gbmj/161-disable-id-like-to-help-from-navigation-menu
https://trello.com/c/uOLsggUt/153-replace-exercise-pdf
https://trello.com/c/3Mtesiay/159-text-in-support-box-results-page
https://trello.com/c/F0uoVRmj/212-terms-of-use-in-footer
https://trello.com/c/QfKpOkfr/154-text-in-exercise-box-results-page
https://trello.com/c/auaQ7e7k/163-coming-soon-button-on-front-page-doesnt-display-properly-on-mobile

### CODE REVIEW

**Review by MadelinTom — APPROVED** [review]
Looks good

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210215-110850 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210215-110850") to [dev](https://console.bluemix.net/apps/0acff2ec-a40e-453a-8151-fb9e5d22e1cf?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit adb5827c75feea71b1d6b4e44771f221b471ba2c

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210302-130622 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210302-130622") to [test](https://console.bluemix.net/apps/bef762e5-4952-4e16-a258-78b99b9fb66d?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit adb5827c75feea71b1d6b4e44771f221b471ba2c

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944") to [prod](https://console.bluemix.net/apps/f1598887-083c-4cac-a3a3-4950b5d061d5?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit adb5827c75feea71b1d6b4e44771f221b471ba2c

**Pull request merged**
