### PR TITLE
force https in non dev environment

### PR DESCRIPTION
**Pull request by matejoslav**
https://trello.com/c/EynBEd0z/218-disable-http-route

### CODE REVIEW

**Comment by matejoslav** [comment]
These should be all the "code" changes, pipeline changes are separately done and those are to just generate routes in correct format and not to force https

**Comment by matejoslav** [comment]
Please check that this works for you thoroughly

**Review by MadelinTom — APPROVED** [review]
looks good

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210507-121945 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210507-121945") to [dev](https://console.bluemix.net/apps/8ee5ceed-bbdc-43ca-bc8c-20e2e9f2d5d7?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 215b5c49ce93f0aff10d545b93cd0428d853ad6b

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210708-095707 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210708-095707") to [test](https://console.bluemix.net/apps/8f252b81-8c47-42f1-9a5b-85e5a6523777?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 215b5c49ce93f0aff10d545b93cd0428d853ad6b

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210709-111250 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210709-111250") to [prod](https://console.bluemix.net/apps/0c01691f-fa4c-4f9f-83ab-49b1a0594f66?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 215b5c49ce93f0aff10d545b93cd0428d853ad6b

**Pull request merged**
