### PR TITLE
Set navbar height to 80px as in the designs

### PR DESCRIPTION
**Pull request by nicholasmorgan**
https://trello.com/c/kfSXwvxC/239-navigation-bar-is-taller

### CODE REVIEW

**Review by MadelinTom — APPROVED** [review]
looks good

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210719-150603 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210719-150603") to [dev](https://console.bluemix.net/apps/b1eddb8a-d0b3-47f1-a906-c7e99dd732ff?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 2e1d2d65ee95f7632e2cc8d81f5bbf0049d1e265

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210720-140402 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210720-140402") to [test](https://console.bluemix.net/apps/cc15165c-b106-4f14-8abc-8afb9a441f1e?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 2e1d2d65ee95f7632e2cc8d81f5bbf0049d1e265

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210720-152423 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210720-152423") to [prod](https://console.bluemix.net/apps/14223cd4-871d-4f82-bc5d-204618d9c0cf?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 2e1d2d65ee95f7632e2cc8d81f5bbf0049d1e265

**Pull request merged**
