### PR TITLE
scroll to top when navigating between pages

### PR DESCRIPTION
**Pull request by matejoslav**
Fixes => https://trello.com/c/LvO1id6W/75-when-pressing-learn-more-button-nadim-gets-taken-to-the-bottom-of-the-look-for-help-page

Removed unnecessary backend call that was not doing anything.

### CODE REVIEW

**Comment by MadelinTom** [comment]
So I have also noticed similar behaviour on master, but now when I go to the 'help' page this is what I get: 
image

The title is now hidden. This is on Chrome

**Comment by MadelinTom** [comment]
I noticed this is a bug: https://trello.com/c/UmmoZA8o/80-navbar-stretches-over-page-content-at-high-resolutions

And because its on master/dev this PR will contain it. Will merge into dev as when the above ticket is complete the fix will be merged into the branch anyway. 

Also had to remove hello-world service locally on my machine to fix merge conflicts

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201216-143237 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201216-143237") to [dev](https://console.bluemix.net/apps/4edc3fe3-2501-4139-b024-b972e5791b94?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit e575420313cc9b4e73915131e8ad069c65a2aa9a

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20201216-152112 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20201216-152112") to [test](https://console.bluemix.net/apps/e5a1b3e6-c509-42a3-bd3a-79626609080d?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit e575420313cc9b4e73915131e8ad069c65a2aa9a

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201217-145052 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201217-145052") to [dev](https://console.bluemix.net/apps/33545de7-22de-43a2-be66-d6f6744fc5b9?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit e575420313cc9b4e73915131e8ad069c65a2aa9a

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747") to [test](https://console.bluemix.net/apps/1d38058e-0941-478d-ab73-1c5c09e8e146?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit e575420313cc9b4e73915131e8ad069c65a2aa9a

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944") to [prod](https://console.bluemix.net/apps/f1598887-083c-4cac-a3a3-4950b5d061d5?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit e575420313cc9b4e73915131e8ad069c65a2aa9a

**Pull request merged**
