### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by JoshBello**

### CODE REVIEW

**Comment by matejoslav** [comment]
@JoshBello not sure what this PR is about, we already have Dockerfile in dev

**Comment by JoshBello** [comment]
@matejoslav apologies for the confusing naming, the changes are on the landing page

**Comment by matejoslav** [comment]
@JoshBello I merged https://github.com/lebanon-relief-project/LRP-web-app/pull/210/files and https://github.com/lebanon-relief-project/LRP-web-app/pull/209/files and they seem to have similar changes, can you check if this PR is still valid please

**Comment by matejoslav** [comment]
Not sure why github is not picking up the newly updated files

**Comment by matejoslav** [comment]
There we go, updated the PR base and it picked up the changes

**Pull request closed without merging**
