### PR TITLE
address bugs

### PR DESCRIPTION
**Pull request by MadelinTom**
https://trello.com/c/sPW4N2lH/275-landing-page-boxes-bugs-and-fixes

### CODE REVIEW

**Comment by nicholasmorgan** [comment]
Screenshot 2021-07-28 at 10 28 39
Screenshot 2021-07-28 at 10 28 56

The min width in pixels is causing the page to be wider than it should be in places

**Review by nicholasmorgan — CHANGES_REQUESTED** [review]
See comments regarding min width in pixels

**Comment by matejoslav** [comment]
@nicholasmorgan is this now ready to be merged?

**Comment by nicholasmorgan** [comment]
@matejoslav yes if you are happy with it please merge

**Comment by matejoslav** [comment]
bug-1
bug-2
bug-3

**Comment by matejoslav** [comment]
Picture 1: the whole 14 days section should be a bit closer together and bit more to the right to match the designs
Picture 2: 2 of the borders appear to be thicker in my browser
Picture 3: The lines should go all the way to the title text just like on the results page

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210804-101047 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210804-101047") to [test](https://console.bluemix.net/apps/9675cafc-afea-463b-a35d-30357ef353f4?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 1bec2ee35da31a11f2321b2f9477128405960b39

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210811-105615 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210811-105615") to [prod](https://console.bluemix.net/apps/ffff1359-e59f-4c64-91a4-b837d66c86e6?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 1bec2ee35da31a11f2321b2f9477128405960b39

**Pull request merged**
