### PR TITLE
update landing page designs

### PR DESCRIPTION
**Pull request by MadelinTom**
as per designs: https://www.figma.com/file/SfRqwuE3GEpM3RkgsH4VLC/Main?node-id=8%3A323

### CODE REVIEW

**Review by nicholasmorgan — CHANGES_REQUESTED** [review]
It looks really good but there are a few small issues

Error Message in the console
Screenshot 2021-07-20 at 14 30 12

The tree is cut off on mobile
Screenshot 2021-07-20 at 14 30 06


Could You also remove the City and Illustration3 images as they are no longer used

**Comment by nicholasmorgan** [comment]
I'm also getting a new package-lock.json generated when installing

**Comment by MadelinTom** [comment]
> I'm also getting a new package-lock.json generated when installing

Think this is an issue with my npm version, can you disregard the package.lock generated (don't commit it). I will update my npm for future PR's

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210720-153010 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210720-153010") to [dev](https://console.bluemix.net/apps/63ba17e6-567c-4400-9a08-3c00ae9ba054?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit c5cb92fb5d14da209d281c199ba386c03395deb3

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210721-075659 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210721-075659") to [test](https://console.bluemix.net/apps/6c9b7747-8886-4624-91f2-11d5248c23f0?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit c5cb92fb5d14da209d281c199ba386c03395deb3

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210724-163313 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210724-163313") to [prod](https://console.bluemix.net/apps/e446a03a-f8e7-4e88-8061-eaf9eba0bb19?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit c5cb92fb5d14da209d281c199ba386c03395deb3

**Pull request merged**
