### PR TITLE
merge repos

### PR DESCRIPTION
**Pull request by matejoslav**
Ticket: https://trello.com/c/xF6C1oV3/49-use-single-runtime-bring-back-end-code-repo-back-into-main-repo

### CODE REVIEW

**Comment by Sandvich** [comment]
Why is this from `merge-repo-updated`? Is `merge-repo` abandoned now? Have the changes been pulled into any other branches?

**Comment by matejoslav** [comment]
yep, I just kept merge-repo as backup, I tried to do the merge in there but my local files went crazy so I pulled dev and did the server changes again.

**Comment by Sandvich** [comment]
Ah, so that's why it doesn't branch from `merge-repo`? You just copied the changes across instead of branching from it?

**Comment by matejoslav** [comment]
pretty much, tbh I could try the old branch again, problem was that the components and tests for them were randomly merged into weird places so I just checked out dev and copied some bits/created some bits again

**Comment by matejoslav** [comment]
Actually let me try it again

**Comment by matejoslav** [comment]
Tried again with merge/rebase, it gets to a point where no npm script work and it merges components randomly on the other branch :D

**Comment by Sandvich** [comment]
Okay, so we're calling the other branch a dead end? I don't have an issue with this, I just want to clarify :)

**Comment by matejoslav** [comment]
oh ok :) yes "merge-repo" is dead end and will be deleted

**Review by Sandvich — APPROVED** [review]
Tested in IBM Cloud, all working as expected.

**Comment by MadelinTom** [comment]
Looks good!

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201111-182704 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201111-182704") to [dev](https://console.bluemix.net/apps/e5324487-24cf-4c0e-9522-e4965cc896ba?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201112-174509 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201112-174509") to [dev](https://console.bluemix.net/apps/d438097c-ddb4-45e8-bdf9-4442713e77d2?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201113-150421 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201113-150421") to [dev](https://console.bluemix.net/apps/ccf8c6a4-8244-4400-8c42-7677e882a220?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201124-122718 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201124-122718") to [dev](https://console.bluemix.net/apps/e7ad1c09-212f-4f68-9639-8073f4cf1781?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201202-101709 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201202-101709") to [dev](https://console.bluemix.net/apps/56ba9f85-8947-4840-bdf0-ccef4ecd4149?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20201208-234333 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20201208-234333") to [test](https://console.bluemix.net/apps/1e190213-4dab-4fe7-9972-03a4bc17b632?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201217-145052 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20201217-145052") to [dev](https://console.bluemix.net/apps/33545de7-22de-43a2-be66-d6f6744fc5b9?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747") to [test](https://console.bluemix.net/apps/1d38058e-0941-478d-ab73-1c5c09e8e146?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944") to [prod](https://console.bluemix.net/apps/f1598887-083c-4cac-a3a3-4950b5d061d5?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 85bdb0a646c323b53184faf33ae9a2597d95e970

**Pull request merged**
