### PR TITLE
minor bug fixes and snags

### PR DESCRIPTION
**Pull request by nicholasmorgan**
Made modal text more readable
Changed email to support@lebanonreliefnetwork.org
Added social media links to icons
Changed social media icons to svg to removed fuzziness
Changed days of wellbeing card from 7 to 14
Disabled wellbeing card button
Added correct icons and sizes to manifest

### CODE REVIEW

**Comment by MadelinTom** [comment]
Looks great!

**Review by MadelinTom — APPROVED** [review]

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210114-172601 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210114-172601") to [dev](https://console.bluemix.net/apps/0716e64d-4194-439f-bff0-e9cdb93db2ab?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 9579ad9900e44c01dca74c1cdd6b66a6e3209d10

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210119-174451 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210119-174451") to [test](https://console.bluemix.net/apps/ffe68851-6e56-40b0-80a3-554fcbfafe9d?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 9579ad9900e44c01dca74c1cdd6b66a6e3209d10

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747") to [test](https://console.bluemix.net/apps/1d38058e-0941-478d-ab73-1c5c09e8e146?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 9579ad9900e44c01dca74c1cdd6b66a6e3209d10

**Pull request merged**
