### PR TITLE
Responsive results page

### PR DESCRIPTION
**Pull request by nicholasmorgan**

### CODE REVIEW

**Review by MadelinTom — CHANGES_REQUESTED** [review]
Looks good - although on mobile/ipad when a number of flashcards are selected (< 5) the yellow bar above the unselected cards dissapears. See image:

image

**Comment by matejoslav** [comment]
> Looks good - although on mobile/ipad when a number of flashcards are selected (< 5) the yellow bar above the unselected cards dissapears. See image:
> 
> image

yeah we have noticed that, it happens because the div "background" that has the opaqued border on top does not fully extend because it is empty technically and we were not able to extend it to match the parent. @nicholasmorgan what did we decide in the end?

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210209-155430 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210209-155430") to [dev](https://console.bluemix.net/apps/35142277-33c3-45ee-8946-720f017c04fa?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 7433a56561d5d58e17f4ac58966cdf0527fbe6f1

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210302-130622 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210302-130622") to [test](https://console.bluemix.net/apps/bef762e5-4952-4e16-a258-78b99b9fb66d?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 7433a56561d5d58e17f4ac58966cdf0527fbe6f1

**Pull request merged**
