### PR TITLE
min width on cards

### PR DESCRIPTION
**Pull request by MadelinTom**
fixes this: 
image

### CODE REVIEW

**Comment by piers-walter-ibm** [comment]
Looks good @MadelinTom

**Review by piers-walter-ibm — APPROVED** [review]

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210804-090336 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210804-090336") to [dev](https://console.bluemix.net/apps/3e849865-f231-4408-abb4-01e8f93f14ae?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 6f6117c7f132a4f2ade493bdf16c52840d06f236

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210804-101047 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210804-101047") to [test](https://console.bluemix.net/apps/9675cafc-afea-463b-a35d-30357ef353f4?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 6f6117c7f132a4f2ade493bdf16c52840d06f236

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210811-105615 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210811-105615") to [prod](https://console.bluemix.net/apps/ffff1359-e59f-4c64-91a4-b837d66c86e6?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 6f6117c7f132a4f2ade493bdf16c52840d06f236

**Pull request merged**
