### PR TITLE
Updated Navbar to closer match designs

### PR DESCRIPTION
**Pull request by piers-walter-ibm**
The navbar more closely matches the designs now. It scales a bit differently to the pages as there's no consistent width on the landing page and the I'm looking for help page. I'm happy to take any feedback and tweak it as necessary.

I've left the landing page as is based on the fact it's currently being redesigned

### CODE REVIEW

**Review by matejoslav — CHANGES_REQUESTED** [review]
Not sure if these changes broke it but the navbar on mobile is no longer aligned to the left

**Comment by MadelinTom** [comment]
Not sure if this was related to one of your changes but now this card has text cut off at the bottom:

image


Might be worth adding a break in card component?

**Comment by MadelinTom** [comment]
Looks like navbar has lost its alignment: 

image

**Comment by piers-walter-ibm** [comment]
Added that back now @MadelinTom

**Review by MadelinTom — APPROVED** [review]

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210921-093646 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210921-093646") to [dev](https://console.bluemix.net/apps/28e62893-ae22-4849-bc6f-9442cc7e05d8?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 5a7239db7f539821eda4c71844ed627e250cba02

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20211124-094333 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20211124-094333") to [test](https://console.bluemix.net/apps/658256c2-ac17-468f-8aca-4181d164dffa?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 5a7239db7f539821eda4c71844ed627e250cba02

**Pull request merged**
