### PR TITLE
Centred the pages so content shouldn't be off to one side any more

### PR DESCRIPTION
**Pull request by piers-walter-ibm**
Applied fixes to the card page and the results page

### CODE REVIEW

**Comment by matejoslav** [comment]
PR-1
PR-2

On 4k(screenshot 1) and 1440px wide screen the bottom footer is not aligned to the content of the page, it should be aligned to the edges of the gray box above

**Review by matejoslav — CHANGES_REQUESTED** [review]
See above

**Comment by matejoslav** [comment]
Home page will be reworked to conform to the new designs so that is looking good

**Comment by matejoslav** [comment]
PR-3

can we make these to always have the same height? might be a bit out of scope for this ticket so let me know

**Comment by matejoslav** [comment]
PR-4
Cards on mobile have too much space on the sides and between other cards, the space should be 18px each side and 18px between cards

**Comment by matejoslav** [comment]
PR-5

The button and gray box should also have 18px on each side

**Comment by piers-walter-ibm** [comment]
Hi @matejoslav, I've updated the footer, cards and contact us sections. The boxes with the blue lines are out of scope for this IMO as the behaviour for when there are two lines in the title isn't in the designs, possibly something to discuss tomorrow

**Review by matejoslav — APPROVED** [review]

**Comment by matejoslav** [comment]
Agreed. I will make a separate ticket to investigate the blue lines stuff.

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210715-185337 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210715-185337") to [dev](https://console.bluemix.net/apps/6eecc318-bd6c-43ca-8418-e89a1a4da05b?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit c280739582816ad8aea689314a7d15536a8044d9

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210716-090706 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210716-090706") to [test](https://console.bluemix.net/apps/2cad90d4-d092-41e4-b067-4e23c89ed619?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit c280739582816ad8aea689314a7d15536a8044d9

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210720-152423 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210720-152423") to [prod](https://console.bluemix.net/apps/14223cd4-871d-4f82-bc5d-204618d9c0cf?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit c280739582816ad8aea689314a7d15536a8044d9

**Pull request merged**
