### PR TITLE
Results page

### PR DESCRIPTION
**Pull request by MadelinTom**
https://trello.com/c/seUzspc1/61-receive-personalised-results

https://www.figma.com/file/SfRqwuE3GEpM3RkgsH4VLC/Main?node-id=8%3A323

Continuing on from https://trello.com/c/hJrEPAjv/6-nadim-02-look-for-help

As Nadim, after I have chosen some cards that represent how I'm feeling, I recieve back with some personalized results

### CODE REVIEW

**Review by matejoslav — APPROVED** [review]

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210120-123256 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210120-123256") to [dev](https://console.bluemix.net/apps/9d76666f-b8ab-48cd-a020-2a8a368abf43?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 62bc9da3cec3e107e91ffb9c893521c87efff380

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-140937 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-140937") to [test](https://console.bluemix.net/apps/02eba03a-981f-4ec7-8e02-0ff171262f62?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 62bc9da3cec3e107e91ffb9c893521c87efff380

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210205-152747") to [test](https://console.bluemix.net/apps/1d38058e-0941-478d-ab73-1c5c09e8e146?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 62bc9da3cec3e107e91ffb9c893521c87efff380

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210303-110944") to [prod](https://console.bluemix.net/apps/f1598887-083c-4cac-a3a3-4950b5d061d5?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 62bc9da3cec3e107e91ffb9c893521c87efff380

**Pull request merged**
