### PR TITLE
Updated Flash Cards Page

### PR DESCRIPTION
**Pull request by piers-walter-ibm**
I've updated the flash cards page to match the designs on Figma

https://trello.com/c/dajRH4E0/241-changes-flashcards-page

### CODE REVIEW

**Comment by matejoslav** [comment]
Screenshot from 2021-06-17 17-03-12
Screenshot from 2021-06-17 17-03-36

On iPad(10 inch) and iPad Pro (12 inch) screen, the '+' button is not visible

**Review by matejoslav — CHANGES_REQUESTED** [review]
see above comment

**Comment by piers-walter-ibm** [comment]
Good spot @matejoslav, I've fixed that now  and added an intermediate view for  iPads with 2 columns

**Review by matejoslav — APPROVED** [review]
Very nice, I added just small css change for the button.

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210617-212210 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210617-212210") to [dev](https://console.bluemix.net/apps/5b8d249c-e228-4893-acd3-ccf3343cf013?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 3349562a9c80452e9b122a5a687dc81c1300d882

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210708-095707 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210708-095707") to [test](https://console.bluemix.net/apps/8f252b81-8c47-42f1-9a5b-85e5a6523777?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 3349562a9c80452e9b122a5a687dc81c1300d882

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210709-111250 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210709-111250") to [prod](https://console.bluemix.net/apps/0c01691f-fa4c-4f9f-83ab-49b1a0594f66?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 3349562a9c80452e9b122a5a687dc81c1300d882

**Pull request merged**
