### PR TITLE
fix issue where menu items are clickable when modal is active

### PR DESCRIPTION
**Pull request by matejoslav**
https://trello.com/c/6cHVAR8Q/237-make-background-of-the-pages-not-clickable-when-the-modal-is-on

### CODE REVIEW

**Review by MadelinTom — APPROVED** [review]
looks good!

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210430-091711 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210430-091711") to [dev](https://console.bluemix.net/apps/6ab0caa3-fbea-4c3e-ad93-6ae758bb56e8?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 466ff3b5178f75993b934219d00aba75f6fb7825

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210708-095707 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210708-095707") to [test](https://console.bluemix.net/apps/8f252b81-8c47-42f1-9a5b-85e5a6523777?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 466ff3b5178f75993b934219d00aba75f6fb7825

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210709-111250 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210709-111250") to [prod](https://console.bluemix.net/apps/0c01691f-fa4c-4f9f-83ab-49b1a0594f66?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 466ff3b5178f75993b934219d00aba75f6fb7825

**Pull request merged**
