### PR TITLE
fixed min width bug

### PR DESCRIPTION
**Pull request by nicholasmorgan**

### CODE REVIEW

**Comment by MadelinTom** [comment]
Homepage still has issues, I am assuming this is what the pr is attempting to fix? : 
image

**Comment by nicholasmorgan** [comment]
This was just to revert back the page width issue. I will add a new PR for the box sizings after todays call to get a consensus if people are happy with it @MadelinTom

**Comment by MadelinTom** [comment]
Okay sounds good! Thanks Nick

**Review by MadelinTom — APPROVED** [review]

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210811-085730 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-dev-20210811-085730") to [dev](https://console.bluemix.net/apps/5b4f306b-16d4-4df2-bf92-bfbe1ec9e7ab?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:dev"), including commit 1590d91f884c23bd10a3e71357055656b78145a6

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210811-093650 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-test-20210811-093650") to [test](https://console.bluemix.net/apps/286f77f9-0f8d-4e9f-96ee-a8a9b753815e?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:test"), including commit 1590d91f884c23bd10a3e71357055656b78145a6

**Comment by arnoldst** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/0a72695f-1fa5-4df5-9d98-aaa218c70126?env_id=ibm:yp:eu-de "lrp-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/66e6d48f-2aa6-41b2-a82d-e4fac4a78dc9 "lrp-toolchain") deployed [LRP-web-app](https://github.com/lebanon-relief-project/LRP-web-app/releases/tag/deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210811-105615 "deploy-ibm-yp-eu-de-Lebanon_Relief_Network-prod-20210811-105615") to [prod](https://console.bluemix.net/apps/ffff1359-e59f-4c64-91a4-b837d66c86e6?env_id=ibm:yp:eu-de "ibm:yp:eu-de:Lebanon_Relief_Network:prod"), including commit 1590d91f884c23bd10a3e71357055656b78145a6

**Pull request merged**
